<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>

<body>
	<script>
		// Promise 构造函数: Promise(excutor) { }
		// (1) executor 函数: 执行器(resolve, reject) => { }
		// (2) resolve 函数: 内部定义成功时我们调用的函数 value => { }
		// (3) reject 函数: 内部定义失败时我们调用的函数 reason => { }
		// 说明: executor 会在 Promise 内部立即同步调用, 异步操作在执行器中执行

		let p = new Promise((resolve, reject) => {
			// 同步调用
			// console.log(111);
			// 修改promise的状态
			reject("error")
		})
		// console.log(222);
		
		// 调用then方法
		// Promise.prototype.then 方法: (onResolved, onRejected) => { }
		// (1) onResolved 函数: 成功的回调函数(value) => { }
		// (2) onRejected 函数: 失败的回调函数(reason) => { }
		// 说明: 指定用于得到成功 value 的成功回调和用于得到失败 reason 的失败回调
		// 返回一个新的 promise 对象
		p.then((value) => {
			console.log(value);

		}, (reason) => {
			console.log(reason);
		})
		// 执行catch方法
		// Promise.prototype.catch 方法: (onRejected) => { }
		// (1) onRejected 函数: 失败的回调函数(reason) => { }

		p.catch(reason => {
			console.log(reason);
		})
	</script>
</body>

</html>